Codeit-sprint2-4-5/global-nomad

public/icons/Icon_minus_time.svg
=> style - 누락된 Icon  추가

src/styles/variables/_colors.scss
=> Style: gray85색상 추가 

public/icons/Icon_popup_check.svg, src/constants/importImages.ts, src/styles/variables/_colors.scss
=> Style: gray55색상추가 profile-image-shadow 색상추가

src/components/common/ReservationTag/ReservationTag.module.scss, src/components/common/ReservationTag/index.tsx
=> faet: 예약 태그 구현

src/components/common/chips/Chips.module.scss, src/components/common/chips/Chips.tsx
- 사용되는 곳이 한정되어 있어서 width: 100% 속성을 적용시켰습니다. 
- 반복되는 부분을 mixin으로 만들까 하다가 그냥 뒀는데 피드백 주시면 반영하겠습니다!
=> feat: Chips 컴포넌트 구현

.gitignore, src/components/common/Input/Input.tsx, src/components/common/Input/inputField.module.scss, src/constants/index.ts, src/constants/inputFieldValidation.ts, src/hooks/index.ts, src/hooks/useToggleButton.ts
기본적으로 width는 100% 입니다. 사용하실 때에 form에 만 width 값을 넣어 쓰시면 됩니다
useToggleButton hook을 만들어 놨습니다. 혹시 필요하다면 가져다가 쓰실 수 있을 거 같아요! 
props 로 더 필요한게 있는지, ...props로 열어놨지만 
더 필요한게 있다면 추가 해야합니다 ㅠ
=> Feat: Input 컴포넌트 추가

src/components/common/search/Search.module.scss, src/components/common/search/Search.tsx
=> feat: enter 눌렀을 때 검색하기 기능 추가

src/components/common/search/Search.module.scss, src/components/common/search/Search.tsx
=> feat: 버튼 컴포넌트 적용

src/pages/api/axios.ts
화면에 보이는 부분만 로컬 콘솔창에 복붙해서 사용하시면 됩니다.
=> Feat/axios intercepter/bjiwon324

src/components/common/title/Title.module.scss, src/components/common/title/Title.tsx
- 넘겨받은 text props으로 타이틀 나오게 구현
=> feat: 공통 - 타이틀 컴포넌트 구현

src/components/common/popup/question/Question.tsx
=> fix: 팝업 컴포넌트 - 경로 수정 및 닫기 추가

src/components/common/popup/confirm/Confirm.tsx, src/components/common/popup/question/Question.tsx
=> fix: 경로 수정 및 닫기 추가

src/components/common/chips/Chips.tsx
=> refactor: Chips 상태 확정 -> 승인 변경

src/components/common/noDataMessgae/NoDataMessage.module.scss, src/components/common/noDataMessgae/NoDataMessage.tsx
=> feat: 데이터 없음 컴포넌트

src/components/common/search/Search.tsx
=> feat: 디바운싱 구현

src/components/common/GNB/GNB.module.scss, src/components/common/GNB/GNB.tsx, src/components/common/avatar/Avatar.module.scss, src/components/common/avatar/Avatar.tsx, src/components/common/layout/Layout.tsx, src/types/myInfo.ts
- Avatar 컴포넌트는 체험상세 페이지의 리뷰? 댓글? 에서도 쓰이는 것 같아서 공통 컴포넌트로 구현했습니다.
- 늦어져서 죄송합니다..
- 피드백 환영합니다!!!
=> Feat: GNB 컴포넌트 구현

src/components/common/Modals/ModalContents/review/Review.tsx
Reverts Codeit-sprint2-4-5/global-nomad#133
=> Revert "예약 정보 모달 수정"

src/components/common/filter/Filter.tsx, src/components/common/filter/FilterDropdown.tsx, src/components/common/menu/MenuDropdown.tsx
=> feat: filter 전체 메뉴 추가

src/pages/signin/index.tsx
=> fix: isLoading 으로 Loading이 기존 요소들을 배제함 주석처리

src/components/common/card/Card.module.scss, src/pages/mypage/[id]/index.tsx
=> fix: mypage index 컴포넌트 추가 및 Card 너비 수정

src/apis/get/getReviews.ts, src/apis/quertKey.ts, src/components/common/floatingBox/FloatingBox.tsx, src/components/domain/activityDetail/activityReviewField/ActivityReviewField.module.css, src/components/domain/activityDetail/activityReviewField/ActivityReviewField.module.css.map, src/components/domain/activityDetail/activityReviewField/ActivityReviewField.module.scss, src/components/domain/activityDetail/activityReviewField/ActivityReviewField.tsx, src/components/domain/activityDetail/activityReviewField/ReviewItem.module.css, src/components/domain/activityDetail/activityReviewField/ReviewItem.module.css.map, src/components/domain/activityDetail/activityReviewField/ReviewItem.module.scss, src/components/domain/activityDetail/activityReviewField/ReviewItem.tsx, src/components/domain/activityDetail/activityReviewField/utill/getEvaluationFromRating.ts
=> Feat : 체험 상세 후기 부분 구현

src/apis/get/getMyNotifications.ts, src/components/common/GNB/GNB.tsx, src/components/common/Modals/ModalContents/notifications/Notifications.module.scss, src/components/common/Modals/ModalContents/notifications/Notifications.tsx, src/components/domain/mypage/myReservations/MyReservations.tsx, src/hooks/useCustomInfiniteQuery.ts
https://github.com/Codeit-sprint2-4-5/global-nomad/assets/131963909/aecea82e-3800-4f22-9187-c0e1a647b010
- 모달 open을위한 GNB 수정과 
- 무한스크롤을 위한 Notification api 함수수정 query 수정 옵저버 추가 return문 조건 수정
=> feat: GNB 알림 및 무한스크롤 구현

src/apis/get/getActivities.ts, src/components/common/cardResource/CardResource.tsx, src/components/common/cardResource/cardResource.module.scss, src/components/common/category/Category.module.scss, src/components/common/dropdownMenu/DropdownMenu.module.scss, src/components/domain/main/MainPage.module.scss, src/components/domain/main/MainPage.tsx, src/components/domain/main/activitiesList/ActivitiesList.module.scss, src/components/domain/main/activitiesList/ActivitiesList.tsx, src/components/domain/main/activitiesList/SearchActivitiesHeader.tsx, src/components/domain/main/banner/Banner.module.scss, src/components/domain/main/banner/Banner.tsx, src/components/domain/main/categoryFilter/CategoryFilter.module.scss, src/components/domain/main/categoryFilter/CategoryFilter.tsx, src/components/domain/main/popularActivitiesList/PopularActivitiesList.module.scss, src/components/domain/main/popularActivitiesList/PopularActivitiesList.tsx, src/hooks/useResponsiveSize.ts, src/pages/index.tsx, src/stores/Activities.ts
=> feat: 메인 페이지 구현

src/components/common/skeleton/Skeleton.tsx
=> fix: 스켈레톤 오류 수정

package-lock.json, src/components/common/GNB/GNB.module.scss, src/components/common/GNB/GNB.tsx, src/components/common/card/Card.module.scss, src/components/common/card/Card.tsx, src/components/common/card/MyActivitiesCard.tsx, src/components/common/cardResource/CardResource.tsx, src/components/domain/kakaoMap/KakaoMap.module.scss, src/components/domain/kakaoMap/KakaoMap.tsx, src/components/domain/mypage/MyCommonCard.module.scss, src/components/domain/mypage/myActivities/MyActivities.tsx, src/components/domain/mypage/myReservations/MyReservations.tsx
=> fix: css수정 modal위치 수정 및 이슈 수정

src/components/common/auth/Auth.tsx, src/components/common/sideNavMenu/SideNavMenu.tsx, src/pages/mypage/[id]/index.tsx
=> feat: Auth컴포넌트 수정 activityDetail/${id} 부분 수정, mypage sideNavMenu initial 값 id로 변경 

src/apis/axios.ts, src/components/common/GNB/GNB.tsx, src/components/common/Modals/Modal.module.scss, src/components/common/Modals/ModalContents/ModalContents.module.scss, src/components/common/Modals/ModalContents/notifications/Notifications.module.scss, src/components/common/Modals/ModalContents/notifications/Notifications.tsx, src/components/common/Modals/index.tsx
=> fix : 모달 위치 , 스타일 수정

src/components/domain/myreservedstatus/Calendar.module.scss, src/components/domain/myreservedstatus/Calendar.tsx
=> fix: 예약현황페이지 ui 수정

src/components/domain/kakaoMap/KakaoMap.tsx, src/pages/mypage/[id]/index.tsx
=> fix: mypages 컴포넌트 중복 코드 제거 

src/stores/Activities.ts
=> fix: Activities zustand create 중괄호 누락

src/components/domain/addActivity/AddActivityForm.tsx, src/components/domain/addActivity/AddressInput.tsx, src/components/domain/addActivity/ImageInput.tsx, src/components/domain/addActivity/ImageList.tsx, src/components/domain/addActivity/ScheduleList.tsx, src/types/activityForm.ts, src/types/index.ts
=>  fix: 스케줄 추가 삭제 수정 

src/components/domain/activityImageField/ImageField.module.scss, src/components/domain/activityImageField/ImageField.tsx
=> feat: imageField 스켈레톤 적용

src/components/domain/activityDetail/activityDescriptionField/ActivityDescriptionField.module.scss, src/components/domain/activityDetail/activityReviewField/ActivityReviewField.module.scss
=> fix : 설명, 후기 깨지는 스타일 변경

src/components/common/GNB/GNB.module.scss, src/components/common/footer/footer.module.scss, src/components/common/layout/Layout.module.scss
=> Feat: 페이지 레이아웃 조정

src/components/domain/account/form/AccountForm.module.scss, src/components/domain/account/form/AccountForm.tsx, src/components/domain/myreservedstatus/Calendar.module.scss, src/components/domain/myreservedstatus/Calendar.tsx
=> Feat: 내정보, 에약현황 모바일 사이즈에서 뒤로가기 버튼 추가 

src/components/common/Input/DateInput.tsx, src/components/common/Modals/ModalContents/dateForm/smallCalendar/SmallCalender.tsx, src/components/common/dropdown/Dropdown.tsx
=> Fix : ref 에러 해결

src/components/common/Modals/ModalContents/dateForm/smallCalendar/smallCalender.module.scss, src/components/common/floatingBox/CountMemberInput.module.scss, src/components/common/floatingBox/FloatingBox.module.scss, src/components/common/floatingBox/FloatingBox.tsx
=> Feat : floatingbox 디자인 수정

src/components/common/Modals/ModalContents/dateForm/smallCalendar/SmallCalender.module.scss
=> fix : 달력 디자인 수정

src/pages/mypage/[id]/index.tsx, src/pages/mypage/index.tsx
=> fix: throttle setTime조정

src/components/common/Modals/ModalContents/dateForm/DateForm.tsx, src/components/common/Modals/ModalContents/dateForm/smallCalendar/SmallCalender.module.scss, src/components/common/Modals/ModalContents/dateForm/smallCalendar/SmallCalender.tsx, src/components/common/Modals/index.tsx, src/components/common/floatingBox/FloatingBox.module.scss, src/components/common/floatingBox/FloatingBox.tsx, src/pages/activityDetail/[id]/index.tsx
=> Feat : 달력 완성

src/components/common/Modals/Modal.module.scss, src/components/common/Modals/ModalContents/reservationInfo/ReservationCard.tsx, src/components/common/Modals/ModalContents/reservationInfo/ReservationInfo.tsx
=> Fix : 모달 오류 수정

src/components/common/floatingBox/FloatingBox.tsx
=> Fix : floatingbox 오류 수정

src/components/common/Modals/ModalContents/review/ReviewForm.tsx, src/components/common/dropdown/Dropdown.tsx, src/components/domain/addActivity/AddActivityForm.tsx
=> Fix : 체험수정 카테고리부분 수정  
